name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://9368aa263462.ngrok-free.app/job/Deploy-Django-on-AWS/build" \
            --user "admin:${{ secrets.JENKINS_API_TOKEN }}"
